title: DLO Portfolio
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  ui:
    output: true
    permalink: /ui/:path/

  advertising:
    output: true
    permalink: /ad/:path/  
